#include "tlpp-core-dev.th"
#include "tlpp-probat.th"

namespace       test.unit.tlpp


/*-------------------------------------------------------------/
DOC Oficial:
https://tdn.totvs.com/display/tec/e-8+-+Error+Log
/-------------------------------------------------------------*/


/*-------------------------------------------------------------/
Teste de exemplo do manual da engine escrito em classe
Exemplo do mesmo teste porem em FUNCTION (com error log)
/-------------------------------------------------------------*/
@TestFixture(owner='sample')
class test_class_errorLog

  private data xValue
  private data xExpected

  public method new()     constructor

  @Test('exemplo de teste com error log')
  @ErrorLog('type mismatch')
  public method ExampleForUseErrorLog()

endclass

method new() class test_class_errorLog
  ::xValue      := Nil
  ::xExpected   := Nil
return self

method ExampleForUseErrorLog() class test_class_errorLog
	sample.tlpp.sampleError()
return .T.


/*-------------------------------------------------------------/
Exemplo do mesmo teste porem em FUNCTION (com error log)
/-------------------------------------------------------------*/
@TestFixture(owner='sample')
@ErrorLog('type mismatch')
function test_function_errorLog()
  sample.tlpp.sampleError()
return .T.

