#include 'tlpp-core.th'
#include 'tlpp-probat.th'

namespace  test.tdd

using namespace tlpp.probat

@TestFixture()
//@skip()
function U_test_tdd_sample_2()

  local xValue
  local xExpected

  xValue    := src.tdd.U_sumNum( 2, 10 )
  xExpected := 12
    assertEquals( xValue, xExpected )

  xValue    := src.tdd.U_sumNum( 20, 100 )
  xExpected := 120
    assertEquals( xValue, xExpected )
    assertGreaterOrEqual( xValue, xExpected )
    assertGreater( xValue, 100 )

return .T.
