#include 'tlpp-core.th'
#include 'tlpp-probat.th'

namespace  test.tdd

using namespace tlpp.probat

@TestFixture()
// @skip() // o Skip nesse exemplo foi necessário antes da implementação de: \tlpp-probat-samples\src\tdd\tdd_sample.tlpp
function U_test_tdd_sample_1()

  local xValue
  local xExpected

  xValue    := tdd.U_sumNum( 1,2 )
  xExpected := 3
    assertEquals( xValue, xExpected )

  xValue    := tdd.U_sumNum( 10,20 )
  xExpected := 30
    assertEquals( xValue, xExpected )

return .T.
