#include 'tlpp-core.th'
#include 'tlpp-probat.th'

namespace  test.tdd

using namespace tlpp.probat

@TestFixture()
//@skip()
function U_test_tdd_sample_1()

  local xValue
  local xExpected

  xValue    := src.tdd.U_sumNum( 1,2 )
  xExpected := 3
    assertEquals( xValue, xExpected )

  xValue    := src.tdd.U_sumNum( 10,20 )
  xExpected := 30
    assertEquals( xValue, xExpected )

return .T.
