#include 'tlpp-core.th'
#include 'tlpp-probat.th'

namespace  test.coverage

using namespace tlpp.probat
  
@TestFixture()
function testCoverage()
  
  local xValue
  local xExpected

  xValue    := src.coverage.srcCoverage( 1 )
  xExpected := 'Aa'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage( 2 )
  xExpected := 'Ee'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage( 3 )
  xExpected := 'Ii'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage( 4 )
  xExpected := 'Oo'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage( 5 )
  xExpected := 'Uu'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage( 0 )
  xExpected := '--'
    assertEquals( xValue, xExpected )

  xValue    := src.coverage.srcCoverage()
  xExpected := '--'
    assertEquals( xValue, xExpected )

return .T.
