#include "tlpp-probat.th"

namespace       test.tlpp


// Tem que ser o primeiro a ser executado
@TestFixture(priority=1)
function U_test_sample_priority_1()

  local cTest     := 'priority=1'
  local xValue    := utils.U_echo( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected )

return .T.


// Tem que ser o ultimo a ser executado
@TestFixture(priority=999)
function U_test_sample_priority_999()

  local cTest     := 'priority=999'
  local xValue    := utils.U_echo( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected )

return .T.
