#include "tlpp-probat.th"

namespace       test.tlpp

using namespace tlpp.probat

@TestFixture( suite="minha_suite" )
function U_test_SUITE_I()
  assertError( 'esse teste jamais deve ser executado em modo all [test] | command SUITE' )
return .T.


@TestFixture( suite="minha_suite" )
function U_test_SUITE_II()
  assertError( 'esse teste jamais deve ser executado em modo all [suite] | command SUITE' )
return .T.
