#include "tlpp-probat.th"

namespace       test.tlpp

/*-------------------------------------------------------------/
DOC Oficial:
https://tdn.totvs.com/display/tec/e-5+-+Suites
/-------------------------------------------------------------*/

@TestFixture( owner='sample', suite="minha_suite_ok" )
function U_test_SUITE_OK()
  tlpp.probat.assertOK( 'Esse teste sera executado somente com modo suite exclusiva' )
return .T.
