#include "tlpp-probat.th"

namespace       test.tlpp

/*-------------------------------------------------------------/
DOC Oficial:
https://tdn.totvs.com/pages/viewpage.action?pageId=654948020
/-------------------------------------------------------------*/
@TestFixture(owner='sample',target="sample_ok.tlpp")
function U_test_sample_function()

  local cTest     := 'test_1'
  local xValue    := src.tlpp.U_sampleOK( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected , 'src.tlpp.U_sampleOK( cTest )' )

return .T.
