#include "tlpp-probat.th"

namespace       test.tlpp

/*-------------------------------------------------------------/
DOC Oficial:
https://tdn.totvs.com/display/tec/e-3+-+Ordem+e+Prioridade
/-------------------------------------------------------------*/


// Tem que ser o primeiro a ser executado
@TestFixture(owner='sample',priority=1)
function U_test_sample_priority_1()

  local cTest     := 'priority=1'
  local xValue    := src.tlpp.U_sampleOK( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected )

return .T.


// Tem que ser o ultimo a ser executado
@TestFixture(owner='sample',priority=999)
function U_test_sample_priority_999()

  local cTest     := 'priority=999'
  local xValue    := src.tlpp.U_sampleOK( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected )

return .T.


// Tem que ser o penultimo a ser executado
@TestFixture(owner='sample',thread="no")
function U_test_sample_no_thread()

  local cTest     := 'no_thread'
  local xValue    := src.tlpp.U_sampleOK( cTest )
  local xExpected := cTest

  tlpp.probat.assertEquals( xValue, xExpected )

return .T.
