#include "tlpp-core.th"
#include "tlpp-probat.th"

namespace   test.api

using namespace tlpp.probat

@TestFixture()
function testRest01()

  local cEndPoint     := '/test/sample'
  local cMethod       := 'GET'
  local cBodyOut      := ''
  local cHeadRet      := ''
  local cRestRet      := ''
  local nStatusCode   := 0
  local nServiceRet   := -1
  local xValue
  local xExpected

  // Executa Endpoint solicitado
  nServiceRet := tlpp.rest.runTestSimple(               ;
                                          @cHeadRet     ,; // HTTP header returned by the service
                                          @cRestRet     ,; // Retorno do servico
                                          @nStatusCode  ,; // HTTP Status Code of the service
                                          cEndPoint     ,;
                                          cMethod       ,;
                                          cBodyOut      ;
                                        )

  if ( nServiceRet >= 0 )

    xValue    := cHeadRet
    xExpected := "HTTP.([\w:\/.]+)([200 OK]+)"
    assertIsRegexPartial( xValue, xExpected )
    
    xValue    := cRestRet
    xExpected := '{"response":"ok"}'
    assertEquals( xValue, xExpected )
    
    xValue    := nStatusCode
    xExpected := 200
    assertEquals( xValue, xExpected )

  else
    assertError( "could not run the REST service" )
  endif

return .T.
